# Generated by Django 2.2.5 on 2019-09-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('userpic', models.CharField(blank=True, max_length=128, null=True, verbose_name='头像')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('mobile', models.CharField(max_length=16, unique=True, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField(blank=True, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('home_city', models.CharField(blank=True, max_length=32, null=True, verbose_name='城市')),
                ('profile', models.CharField(blank=True, max_length=256, null=True, verbose_name='个人简介')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
