# Generated by Django 2.2.5 on 2019-09-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190929_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userid',
            new_name='user',
        ),
    ]
